### ISSUE TITLE
Channel Point TTS stops after the first successful redemption

### ISSUE THREAD

**Issue by Eulentier161** [daftmaple/sound-trigger-channel-points#12]
The first TTS redemption works fine but every additional test wont trigger a voice event. The log still shows 'User: <user> redeemed TTS'.

**Comment by daftmaple** [comment]
Apparently this happened recently somewhere but I'm unsure what could be the breaking point. There are multiple possibilities:

- the event is not emitted properly within the server code itself (there was a bugfix recently which involves event emitter)
- the TTS engine breaks (possible breaking point, but usually logs something)
- socket.io failed to emit to the client hence client doesn't request the sound file. I know that the current socket.io package has some vulnerabilities (planning to update it soon, never breaks but still possible)
- there is something within the `/sfx` page which prevents the sound to be played due to [browser autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) (I don't think this is the case)

A quick way to investigate this is by checking the network tab on page inspection and see whether there's any request when TTS/soundboard gets redeemed.

My current plan is to replace the current TTS engine to use [Mozilla TTS docker](https://github.com/synesthesiam/docker-mozillatts), which seems to be more reliable. I also need to replace the current implementation twitch api and pubsub handler for a well-polished package like [this](https://d-fischer.github.io/twitch/)

**Comment by daftmaple** [comment]
I just found out that this happened because of the server code that uses `EventEmitter.once()` instead of `.on()`. Will fix this
